### ISSUE TITLE
Process-status request for not existing entity-id returns http code 200 [2379]

### ISSUE THREAD

**Issue by RCarisBuyBay** [developersbolcom/developersbolcom.github.io#16]
**Endpoint**
Process-status (by entity_id & event_type) https://api.bol.com/retailer/public/redoc/v3#operation/get-process-status

**Problem**
When using a not existing entity-id the response code is 200. I think this should be a 404 NOT_FOUND error because the entity from my example not exists.

**Our request**
```
[httplog] Connecting: api.bol.com:443
[httplog] Sending: GET http://api.bol.com:443/retailer-demo/process-status?entity-id=000000000&event-type=CREATE_OFFER
[httplog] Header: content-type: application/vnd.retailer.v3+json
[httplog] Header: accept: application/vnd.retailer.v3+json
[httplog] Header: authorization: Bearer *
[httplog] Header: connection: close
[httplog] Header: host: api.bol.com
[httplog] Header: content-length: 0
[httplog] Data: 
[httplog] Status: 200
[httplog] Benchmark: 0.024766 seconds
[httplog] Header: date: Tue, 12 Mar 2019 14:54:10 GMT
[httplog] Header: server: Apache Tomcat
[httplog] Header: x-xss-protection: 1; mode=block
[httplog] Header: x-content-type-options: nosniff
[httplog] Header: x-frame-options: SAMEORIGIN
[httplog] Header: strict-transport-security: max-age=31536000
[httplog] Header: x-application-context: Edge:8090
[httplog] Header: content-type: application/vnd.retailer.v3+json;charset=UTF-8
[httplog] Header: vary: Accept-Encoding,User-Agent
[httplog] Header: connection: close
[httplog] Header: transfer-encoding: chunked
[httplog] Response: {}
```
**The result we expected**
We expected to get a 404 NOT_FOUND error because this entity not exists. Otherwise users may think everything went well because it's returning a 200 code without any error.

**Comment by gvantuijl** [comment]
Hi,

An event/entity can have more than 1 process statuses. When you provide a fake entity/event, returning a 404 would be incorrect. The API basically says: here is the list that complies to the data you provided. Because you provided a fake entity/event, the result set is obviously empty.

If you would make the same call to and endpoint that only retrieves a single object (like the process status id endpoint), we agree with your implementation suggestion. However because this endpoint provides a set of results, the API returns the results with a success.

**Comment by joostvandermeer** [comment]
I will move this issue to done. Please let us know if you have any follow-up questions, we can alway re-open it.
