### ISSUE TITLE
Raise "Allowed clock skew"

### ISSUE THREAD

**Issue by JeroenVanLeusden** [developersbolcom/developersbolcom.github.io#20]
Quite often we get a 401 - UNAUTHORIZED response. This happens if the clocks on both systems don't match exactly. Can this threshold be raised to allow a slight difference?

Already had contact with @idebruijn over email.

`GET https://api.bol.com/retailer/orders?page=1&fulfilment-method=FBR` resulted in a `401 JWT expired at 2019-03-13T16:55:03Z. Current time: 2019-03-13T16:55:03Z, a difference of 27 milliseconds.  Allowed clock skew: 0 milliseconds.: `
 
`GET https://api.bol.com/retailer/orders?page=1&fulfilment-method=FBR` resulted in a `401 JWT expired at 2019-03-14T09:25:03Z. Current time: 2019-03-14T09:25:03Z, a difference of 12 milliseconds.  Allowed clock skew: 0 milliseconds.: `
 
`GET https://api.bol.com/retailer/orders?page=1&fulfilment-method=FBR` resulted in a `401 JWT expired at 2019-03-14T11:55:03Z. Current time: 2019-03-14T11:55:08Z, a difference of 5359 milliseconds.  Allowed clock skew: 0 milliseconds.: `
 
`GET https://api.bol.com/retailer/orders?page=1&fulfilment-method=FBR` resulted in a `401 JWT expired at 2019-03-14T12:15:03Z. Current time: 2019-03-14T12:15:03Z, a difference of 39 milliseconds.  Allowed clock skew: 0 milliseconds.: `

**Comment by JeroenVanLeusden** [comment]
@jwalgemoed I see the limit is now 1000 milliseconds. Is it possible to raise this even further? We still see the notices on different servers with up to 5 seconds difference.

```
Client error: `POST https://api.bol.com/retailer/offers` resulted in a `401 JWT expired at 2019-04-04T13:49:04Z. Current time: 2019-04-04T13:49:08Z, a difference of 3250 milliseconds.  Allowed clock skew: 1000 milliseconds.: ` response:
 (truncated...)

Client error: `PUT https://api.bol.com/retailer/offers/3df43269-ba24-4be6-8466-a90e7b8598c6` resulted in a `401 JWT expired at 2019-04-04T13:43:02Z. Current time: 2019-04-04T13:43:07Z, a difference of 4605 milliseconds.  Allowed clock skew: 1000 milliseconds.: ` response:
 (truncated...)

Client error: `PUT https://api.bol.com/retailer/offers/df70e1ce-dc74-4c25-a59b-ea8e07dda7df` resulted in a `401 JWT expired at 2019-04-04T13:37:04Z. Current time: 2019-04-04T13:37:07Z, a difference of 2938 milliseconds.  Allowed clock skew: 1000 milliseconds.: ` response:
 (truncated...)
```

**Comment by jwalgemoed** [comment]
Hi Jeroen, thank you for you message. It's interesting to see the amount of clock skew going up, the cases we've seen before were well in the range of 0-1000ms. We've also launched an investigation to see why some servers have this much time difference to begin with. We'll either adjust the clock skew to allow enough clock skew for this to not be an issue, or (preferably) make sure that our servers do not wander out of sync.

**Comment by jwalgemoed** [comment]
@JeroenVanLeusden we've checked internally if our server landscape might be suffering from servers wandering out of sync. We've just concluded that this seems to be the case, we are also looking into the fact that server may/may not have been out of sync in the past. 

Can you let us know if you are still seeing these errors, and if yes, what the highest amount of clock skew is that you've encountered? We could change the clock skew allowances, if they are within acceptable bounds.

**Comment by JeroenVanLeusden** [comment]
Will keep an eye on the logs and update this ticket when necessary.

**Comment by jwalgemoed** [comment]
Thank you!

**Comment by JeroenVanLeusden** [comment]
Still see these errors when pushing large amounts of offers, although it looks like the amount of errors is reduced compared to last week. Most errors are between 1 and 10 seconds with an occasional spike to up to 30 seconds.

**Comment by jwalgemoed** [comment]
@JeroenVanLeusden Hi Jeroen, I meant to get back to you earlier on this, but we've been busy checking all our systems. The issues we have hear is that the tool we use to parse the tokens is giving an unclear message. 

Basically this process is what we would expect from our setup, users request a token and use this to do requests. In order to defend against replay attacks (where someone somehow intercepts a token and is doing requests on your behalf) we cycle the tokens every few minutes. When requesting a token the response will give you a token and tell you how long it will be valid: "expires_in": 299 (in seconds, so in this case 5 minutes). 

The error message you get is the normal error message that is returned when the token expires, as the server is now determining that the token has passed its validity. Because all clocks are completely in sync, this works fine -- we have backend checks verifying that this is the case. 

The message returned simply describes how much you are over the limit. Let's look at an example: 

```
GET https://api.bol.com/retailer/orders?page=1&fulfilment-method=FBR resulted in a 401 JWT expired at 2019-03-13T16:55:03Z. Current time: 2019-03-13T16:55:03Z, a difference of 27 milliseconds. Allowed clock skew: 0 milliseconds.
```

This message now states that the request came in 27 milliseconds after the token expired, meaning you can't use it anymore. Hence the 401 (unauthorized) error code. The clock skew part is added to the message by the framework for clarity -- it doesn't signal that there is an issue with clock skew, it just signals how much clock skew we are allowing. 

So, by adding 1000ms to the allow clock skew settings, we are not able to deal with (at most) 1 second of skew when it comes to the server clock. Again, this isn't the case, all are in sync. How you as a use should deal with the API is as follows: Acquire a token and do requests with it. Once it expires (either by checking for the inevitable 401 or to prevent this, use the expires_in value returned to know when to request a new token) you simply need to request a new token.

It took a while to figure this out, as it did look like an issue at our end, but I guess we both simply misinterpreted the message. I'll look into updating the documentation to reflect how this works in a more explicit way. Hope this helps!
